#gt915 touchpanel driver


obj-$(CONFIG_TOUCHPANEL_GOODIX_GT5688)	+= gt1x_driver.o
#obj-$(CONFIG_GT5688_TOUCHPANEL_DRIVER)	+= gt1x_extents.o
#obj-$(CONFIG_GT5688_TOUCHPANEL_DRIVER)	+= gt1x_generic.o
#obj-$(CONFIG_GT5688_TOUCHPANEL_DEBUG)	+= gt1x_tools.o
#obj-$(CONFIG_GT5688_TOUCHPANEL_UPDATE)	+= gt1x_update.o