#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_GOODIX_GT5688) += Goodix_gt5688/
obj-$(CONFIG_TOUCHPANEL_GOODIX_GT9286) += GT9286/
obj-$(CONFIG_TOUCHPANEL_GOODIX) += goodix_common.o
obj-$(CONFIG_TOUCHPANEL_GOODIX) += goodix_tool.o

#endif
