#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_NOVA) += novatek_common.o
obj-$(CONFIG_TOUCHPANEL_NOVA_NT36672) += NT36672/
obj-$(CONFIG_TOUCHPANEL_NOVA_NT36525) += NT36525/
obj-$(CONFIG_TOUCHPANEL_NOVA_NT36672_NOFLASH) += NT36672_noflash/

#endif
