# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
oplus_bsp_mxm_up-y      += hall_mxm1120_up.o
obj-$(CONFIG_MXM_UP)	+= oplus_bsp_mxm_up.o
oplus_bsp_mxm_down-y    += hall_mxm1120_down.o
obj-$(CONFIG_MXM_DOWN)	+= oplus_bsp_mxm_down.o
