ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_jpeg
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_jpeg/jpeg_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_jpeg/jpeg_hw/
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_jpeg/jpeg_hw/jpeg_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_jpeg/jpeg_hw/jpeg_dma_hw

obj-$(CONFIG_SPECTRA_CAMERA) += jpeg_dma_dev.o jpeg_dma_core.o jpeg_dma_soc.o
