ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_cpas

obj-$(CONFIG_SPECTRA_CAMERA) += cam_camsstop_hw.o
