#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ST_FST1BA90A) += fst1ba90a/
obj-$(CONFIG_TOUCHPANEL_ST) += st_common.o

#endif
