ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_lrme
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_lrme/lrme_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += cam_lrme_hw_dev.o cam_lrme_hw_core.o cam_lrme_hw_soc.o
