obj-$(CONFIG_OPLUS_TRIKEY_HALL)	+= ist_hall_ic/
obj-$(CONFIG_OPLUS_TRIKEY_HALL) += hall_ic/
oplus_bsp_tri_key-y             += oplus_tri_key.o
obj-$(CONFIG_OPLUS_TRIKEY_MAIN)      += oplus_bsp_tri_key.o
obj-$(CONFIG_OPLUS_TRI_STATE_KEY)     += tri_state_key.o
