#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_FOCAL) += focal_common.o
obj-$(CONFIG_TOUCHPANEL_FOCAL_FT8006) += FT8006/


#endif
