#fingerprint_detect should before fpc1022
obj-$(CONFIG_FINGERPRINT_DETECT)    += fingerprint_detect/
obj-$(CONFIG_FINGERPRINT_FPC)	    += fpc/
obj-$(CONFIG_FINGERPRINT_GOODIX)	+= goodix/
obj-$(CONFIG_FINGERPRINT_SILEAD)	+= silead/
obj-$(CONFIG_MSM_QBT1000) += qbt1000/