#
# Makefile for the FTS touchscreen driver.
#

obj-$(CONFIG_TOUCHPANEL_ST_FST1BA90A) += ftsCompensation.o ftsCore.o ftsError.o ftsFrame.o ftsIO.o ftsTest.o ftsTime.o ftsTool.o ftsFlash.o ftsGesture.o

