obj-y += coretech_helper.o
obj-$(CONFIG_ADJ_CHAIN) += adj_chain/
obj-$(CONFIG_CRPL) += crpl/
obj-$(CONFIG_DEFRAG_HELPER) += defrag/
obj-$(CONFIG_OPCHAIN) += opchain/
obj-$(CONFIG_HOUSTON) += houston/
obj-$(CONFIG_MEMPLUS) += memplus/
obj-$(CONFIG_FSC) += fsc/
