obj-$(CONFIG_OEM_BOOT_MODE) += boot_mode.o
ifdef CONFIG_OEM_DEBUG_SUPPORT
# oem trace
obj-$(CONFIG_OEM_TRACE_SUPPORT) += oem_trace.o
endif

obj-$(CONFIG_WB_KERNEL_LOG) += wb_kernel_log.o

obj-y += coretech/
