ccflags-y += -Idrivers/media/platform/msm/camera_7150
ccflags-y += -Idrivers/media/platform/msm/camera_7150/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/camera_7150/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
