ccflags-y += -Idrivers/media/platform/msm/camera_8150_op
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/camera_8150_op/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
