ifeq ($(CONFIG_OPLUS_CHARGER_MTK6763)_$(CONFIG_OPLUS_CHARGER_MTK6771),n_n)
obj-y	+= oplus_pic16f.o
endif

obj-y	+= oplus_n76e.o
obj-y	+= oplus_vooc_fw.o
obj-y	+= oplus_stm8s.o
obj-y	+= oplus_rk826.o
obj-y	+= oplus_op10.o
obj-y	+= oplus_rt5125.o